version: '2'
services:
  postgres:
    image: "postgres:9.6"
    environment:
      - "POSTGRES_USER=dashboard"
      - "POSTGRES_DB=dashboard"
      - "POSTGRES_PASSWORD=dashboard"
    volumes:
      - "/srv/docker/app/postgres:/var/lib/postgresql/data"
    restart: "always"
  appboard:
    image: "pezzak/appboard:0.0.1"
    volumes:
      - "/srv/docker/app/config/config.py:/app/config.py"
    links:
      - "postgres:postgres"
    ports:
      - "8000:8000"
    restart: "always"
